[package]
name = "string_replace_rs"
version = "0.1.0"
authors = ["Boss <bossnathakorn@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4.3"
